In [4]:
import pandas as pd

df = pd.read_csv("../data/raw/Global_SuperStore.csv", encoding="latin1")

In [5]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11-08-2016,11-11-2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,06-12-2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10-11-2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [6]:
df[["Order Date", "Ship Date"]].head()

   Order Date   Ship Date
0  11-08-2016  11-11-2016
1  11-08-2016  11-11-2016
2  06-12-2016   6/16/2016
3  10-11-2015  10/18/2015
4  10-11-2015  10/18/2015

In [7]:
df.shape

(9994, 21)

In [8]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   str
 3   Ship Date      9994 non-null   str
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.6 MB

In [10]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [11]:
df.describe(include="object")

C:\Users\USER\AppData\Local\Temp\ipykernel_8120\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name
count,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994
unique,5009,1237,1334,4,793,793,3,1,531,49,4,1862,3,17,1850
top,CA-2017-100111,09-05-2016,12/16/2015,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope
freq,14,38,35,5968,37,37,5191,9994,915,2001,3203,19,6026,1523,48

In [12]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df['Sales'].min(),df['Sales'].max()

(np.float64(0.444), np.float64(22638.48))

In [15]:
df["Profit"].min(),df["Profit"].max()

(np.float64(-6599.978), np.float64(8399.976))

In [16]:
df["Customer ID"].nunique()

793

In [17]:
df["Product ID"].nunique()

1862

In [18]:
df["Order ID"].nunique()

5009

In [19]:
df["Country"].nunique()

1

In [20]:
df["City"].nunique()

531

In [21]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [22]:
df[["Order Date", "Ship Date"]].head(10)

   Order Date   Ship Date
0  11-08-2016  11-11-2016
1  11-08-2016  11-11-2016
2  06-12-2016   6/16/2016
3  10-11-2015  10/18/2015
4  10-11-2015  10/18/2015
5  06-09-2014   6/14/2014
6  06-09-2014   6/14/2014
7  06-09-2014   6/14/2014
8  06-09-2014   6/14/2014
9  06-09-2014   6/14/2014

In [26]:
df["Order Date"].head(10)

0    11-08-2016
1    11-08-2016
2    06-12-2016
3    10-11-2015
4    10-11-2015
5    06-09-2014
6    06-09-2014
7    06-09-2014
8    06-09-2014
9    06-09-2014
Name: Order Date, dtype: str

In [28]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="mixed"
)

In [29]:
print(df["Order Date"].head())
print(df["Order Date"].dtype)

0   2016-11-08
1   2016-11-08
2   2016-06-12
3   2015-10-11
4   2015-10-11
Name: Order Date, dtype: datetime64[us]
datetime64[us]

In [25]:
df["Order Date"].unique()[:10]

<StringArray>
['11-08-2016', '06-12-2016', '10-11-2015', '06-09-2014',  '4/15/2017',
 '12-05-2016', '11/22/2015', '11-11-2014',  '5/13/2014',  '8/27/2014']
Length: 10, dtype: str

In [30]:
df["Order Date"] = pd.to_datetime(df["Order Date"])

In [31]:
df["Order Date"].min()

Timestamp('2014-01-03 00:00:00')

In [32]:
df["Order Date"].max()

Timestamp('2017-12-30 00:00:00')

In [33]:
print("Earliest Order Date:", df["Order Date"].min())
print("Latest Order Date:", df["Order Date"].max())

Earliest Order Date: 2014-01-03 00:00:00
Latest Order Date: 2017-12-30 00:00:00

In [34]:
df.dtypes

Row ID                    int64
Order ID                    str
Order Date       datetime64[us]
Ship Date                   str
Ship Mode                   str
Customer ID                 str
Customer Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal Code               int64
Region                      str
Product ID                  str
Category                    str
Sub-Category                str
Product Name                str
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [36]:
df["Ship Date"] = pd.to_datetime(df["Ship Date"], format="mixed")

In [37]:
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [38]:
df.dtypes

Row ID                    int64
Order ID                    str
Order Date       datetime64[us]
Ship Date        datetime64[us]
Ship Mode                   str
Customer ID                 str
Customer Name               str
Segment                     str
Country                     str
City                        str
State                       str
Postal Code               int64
Region                      str
Product ID                  str
Category                    str
Sub-Category                str
Product Name                str
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [39]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [40]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

In [41]:
df.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='str')

In [42]:
#derived col - delivery days
df["delivery_days"] = (df["ship_date"] - df["order_date"]).dt.days

In [43]:
df[["order_date", "ship_date", "delivery_days"]].head()

  order_date  ship_date  delivery_days
0 2016-11-08 2016-11-11              3
1 2016-11-08 2016-11-11              3
2 2016-06-12 2016-06-16              4
3 2015-10-11 2015-10-18              7
4 2015-10-11 2015-10-18              7

In [44]:
df["delivery_days"].describe()

count    9994.000000
mean        3.958175
std         1.747567
min         0.000000
25%         3.000000
50%         4.000000
75%         5.000000
max         7.000000
Name: delivery_days, dtype: float64

In [45]:
df["order_year"] = df["order_date"].dt.year
df["order_month"] = df["order_date"].dt.month
df["order_month_name"] = df["order_date"].dt.month_name()
df["order_quarter"] = df["order_date"].dt.quarter
df["order_day"] = df["order_date"].dt.day
df["order_day_name"] = df["order_date"].dt.day_name()

In [46]:
df[[
    "order_date",
    "order_year",
    "order_month",
    "order_month_name",
    "order_quarter",
    "order_day",
    "order_day_name"
]].head()

,order_date,order_year,order_month,order_month_name,order_quarter,order_day,order_day_name
0,2016-11-08,2016,11,November,4,8,Tuesday
1,2016-11-08,2016,11,November,4,8,Tuesday
2,2016-06-12,2016,6,June,2,12,Sunday
3,2015-10-11,2015,10,October,4,11,Sunday
4,2015-10-11,2015,10,October,4,11,Sunday

In [47]:
df["profit_margin"] = (df["profit"] / df["sales"]) * 100

In [48]:
df[["sales", "profit", "profit_margin"]].head()

      sales    profit  profit_margin
0  261.9600   41.9136          16.00
1  731.9400  219.5820          30.00
2   14.6200    6.8714          47.00
3  957.5775 -383.0310         -40.00
4   22.3680    2.5164          11.25

In [49]:
(df["sales"] < 0).sum()

np.int64(0)

In [50]:
(df["quantity"] < 0).sum()

np.int64(0)

In [51]:
df["discount"].describe()

count    9994.000000
mean        0.156203
std         0.206452
min         0.000000
25%         0.000000
50%         0.200000
75%         0.200000
max         0.800000
Name: discount, dtype: float64

In [52]:
(df["delivery_days"] < 0).sum()

np.int64(0)

In [54]:
df.to_csv("../data/cleaned/global_superstore_cleaned.csv", index=False)